services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  config-server:
    build:
      context: ./configServer
      dockerfile: Dockerfile
    image: cryptocollector/config-server:latest
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=native
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 12

  discovery-server:
    build:
      context: ./discoveryServer
      dockerfile: Dockerfile
    image: cryptocollector/discovery-server:latest
    env_file:
      - .env
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 12

  api-gateway:
    build:
      context: ./apiGateWay
      dockerfile: Dockerfile
    image: cryptocollector/api-gateway:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 12

  auth-service:
    build:
      context: ./microServices/auth-microServices
      dockerfile: Dockerfile
    image: cryptocollector/auth-service:latest
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  postgres-data:
    driver: local

networks:
  microServices:
    driver: bridge