spring:
    application:
            name: auth-microServices
    config:
        import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

    profiles:
        active: dev
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

management:
    endpoints:
        web:
            exposure:
                include: health,info

eureka:
    client:
        service-url:
            defaultZone: http://discovery-server:8761/eureka/
    instance:
        prefer-ip-address: false