spring:
    application:
            name: auth-microServices
    config:
        import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

    profiles:
        active: dev
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

management:
    endpoints:
        web:
            exposure:
                include: health,info

# Configuración de Springdoc/Swagger para trabajar detrás del API Gateway
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
    use-management-port: false
    use-root-path: false
server:
    forward-headers-strategy: framework

eureka:
    client:
        service-url:
            defaultZone: http://discovery-server:8761/eureka/
    instance:
        prefer-ip-address: false