server:
  port: 8080

spring:
  application:
    name: apiGateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters: []
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8761/eureka/"
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 horas

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO