server:
  port: 8080

spring:
  application:
    name: apiGateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters: []
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # AUTH SERVICE ROUTES
        - id: auth-public
          uri: lb://auth-microservices
          predicates:
            - Path=/api/auth/register, /api/auth/login
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/$\{segment}

        # Auth - Swagger UI
        - id: auth-swagger-ui
          uri: lb://auth-microservices
          predicates:
            - Path=/auth/swagger-ui/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - PreserveHostHeader
            - AddRequestHeader=X-Forwarded-Prefix, /auth

        # Auth - API Docs
        - id: auth-api-docs
          uri: lb://auth-microservices
          predicates:
            - Path=/auth/v3/api-docs/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - AddRequestHeader=X-Forwarded-Prefix, /auth

        # CRYPTO COLLECTOR ROUTES
        # Crypto - Endpoints públicos (sin autenticación)
        - id: crypto-public
          uri: lb://crypto-collector-micro
          predicates:
            - Path=/api/public/**
          filters:
            - RewritePath=/api/public/(?<segment>.*), /api/public/$\{segment}

        # Crypto - Endpoints protegidos
        - id: crypto-protected
          uri: lb://crypto-collector-micro
          predicates:
            - Path=/api/crypto/**, /api/cache/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}

        # Crypto - Swagger UI (sin trailing slash en segment)
        - id: crypto-swagger-ui
          uri: lb://crypto-collector-micro
          predicates:
            - Path=/crypto/swagger-ui/**
          filters:
            - RewritePath=/crypto/(?<segment>.*), /$\{segment}
            - PreserveHostHeader
            - AddRequestHeader=X-Forwarded-Prefix, /crypto

        # Crypto - API Docs
        - id: crypto-api-docs
          uri: lb://crypto-collector-micro
          predicates:
            - Path=/crypto/v3/api-docs/**
          filters:
            - RewritePath=/crypto/(?<segment>.*), /$\{segment}
            - AddRequestHeader=X-Forwarded-Prefix, /crypto

      # Configuración global de CORS
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: ${JWT_SECRET:devSecretChangeMe}
  expiration: ${JWT_EXPIRATION:86400000} # 24 horas

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO
    com.netflix.discovery: INFO
