spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cryptodata}}
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:postgres}
        jpa:
            hibernate:
                ddl-auto: update
            show-sql: true

    jwt:
        secret: ${JWT_SECRET:change_this_to_a_real_secret}
        expiration: ${JWT_EXPIRATION:86400000}

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html

logging:
    level:
        root: INFO