spring:
  profiles:
    active: native
  application:
    name: configServer
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config

server:
  port: 8888