spring:
    application:
            name: crypto-collector-micro
    config:
        import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

    profiles:
        active: dev
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

    # Redis Configuration
    data:
        redis:
            host: ${SPRING_DATA_REDIS_HOST:localhost}
            port: ${SPRING_DATA_REDIS_PORT:6379}
            timeout: 2000ms
            jedis:
                pool:
                    max-active: 8
                    max-idle: 8
                    min-idle: 0
                    max-wait: -1ms

    # Cache Configuration
    cache:
        type: redis
        redis:
            time-to-live: 300000
            cache-null-values: false

management:
    endpoints:
        web:
            exposure:
                include: health,info

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
    use-management-port: false
    use-root-path: false
server:
    forward-headers-strategy: framework

eureka:
    client:
        service-url:
            defaultZone: http://discovery-server:8761/eureka/
    instance:
        prefer-ip-address: false